version: "3.8"

services:
  app:
    build:
      context: app
    environment:
      HOST: 0.0.0.0
      DB_HOST: db
      DB_PORT: 3306
    restart: always
    ports:
      - 8888:8888
    networks:
      - app-net
    tty: true
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-net:
    driver: bridge 
